spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/webdb?serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 0117fjxcbryl
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mycharge.trainingmanagementplatform.mapper
  config-location: classpath:mybatis-config.xml