spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/second?serverTimezone=GMT%2B8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix:
      classpath: /templates/
    mode: HTML
    suffix: .html
    encoding: utf-8
    cache: false

#  mvc:
#    static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mycharge.trainingmanagementplatform.mapper
  config-location: classpath:mybatis-config.xml

