spring:
  datasource:
    url: jdbc:mysql://139.219.1.43:3306/wecharge?serverTimezone=GMT%2B8&allowMultiQueries=true
    username: 46
    password: WeCharge46
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    cache: false
    prefix:
      classpath: /templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mycharge.trainingmanagementplatform.mapper
  config-location: classpath:mybatis-config.xml